language: java
dist: bionic
jdk: openjdk11
env:
  global:
    - PYENV_VERSION=3.7
install:
  - pip3 install --user pre-commit
script:
  - pre-commit run --all-files --verbose
  - mvn clean verify
  - mvn clean package
  - |
  echo 'settings:
  regions: [us-east-1]
  output: cfn-schemas' > cfg.yml
  - java -jar target/aws-cloudformation-template-schema-1.0-SNAPSHOT-jar-with-dependencies.jar --config-file cfg.yml
